USER: "{{ lookup('env', 'USER') }}"
HOME: "{{ lookup('env', 'HOME') }}"
PASS: "{{ vault_PASS }}"

packages:
  - neovim
  - zsh
  - zsh-syntax-highlighting
  - stow
  - tmux
  - docker
  - docker-compose
  - tree
